

inventorySeed = [{
    brand:'Nemo',
    name: 'Fillo Pillow',
    price: 44.95,
    type: 'Pillow',
    rating: 4.5,
    features: ['Synthetic', 'air'],
    description: 'Inflates easily and packs down as small as a russet potato in its integrated stuff sack, making it ideal for backpacking and travel adventures',
    size: 'small',
    available: true,
    color: 'blue'
},
{
    brand:'Ther-a-Rest',
    name: 'Compressible Pillow',
    price: 36.95,
    type: 'Pillow',
    rating: 4.6,
    features: ['Synthetic', 'Polyurethane foam fill' ],
    description: 'Luxuriously soft, 60% recycled polyester cover is filled with supportive and compressible foam; foam is upcycled from excess material used in sleeping pad production',
    size: 'medium',
    available: true,
    color: 'mushroom / green'
},
{
    brand:'Hest',
    name: 'Camp Pillow',
    price: 89.00,
    type: 'Pillow',
    rating: 4.9,
    features: ['Synthetic', 'Enhanced memory foam/polyester'],
    description: 'Design provides optimal support, comfy alignment, a soft surface and plenty of airflow to maintain a perfect sleeping temperature',
    size: 'large',
    available: false,
    color: 'blue'
},
{
    brand:'Sea to Summit',
    name: 'Aeros Down Pillow',
    price: 89.95,
    type: 'Pillow',
    rating: 4.3,
    features: ['Filled Down', '10-denier nylon top', '20-denier nylon base', 'thermoplastic urethane bladder'],
    description: 'As you drift off to sleep, your pillow won\'t slide off of your Sea to Summit mat (not included): the PillowLock™ system keeps your pillow right where it belongs',
    size: 'deluxe',
    available: true,
    color: 'grey'
},
{
    brand:'The North Face',
    name: 'Wawona 6 Tent',
    price: 500.00,
    type: 'Camping Tents',
    rating: 4.4,
    features: ['Color-coded poles and trims make setup simple', 'Hybrid double-wall construction and a large mesh front door offer superior ventilation'],
    description: 'Named after an iconic redwood, the refreshed The North Face Wawona 6 tent has gone from single- to double-wall construction. Plus, its huge vestibule makes it feel less like a tent, more like a home.',
    size: 'six-person',
    available: true,
    color: 'orange'
},
{
    brand:'REI Co-op',
    name: 'Base Camp 4 Tent',
    price: 474.00,
    type: 'Camping Tents',
    rating: 4.4,
    features: ['Rugged materials and proven architecture are designed to be highly stable while maximizing interior livability in this full-featured tent'],
    description: 'Dispersed camping, vehicle-supported overnights and campground stays—whatever your flavor of adventure, our member-favorite REI Co-op Base Camp 4 tent offers a robust shelter in any weather.',
    size: 'four-person',
    available: false,
    color: 'yellow'
},
{
    brand:'Alpine Mountain Gear',
    name: 'Weekender Tent 3',
    price: 54.73,
    type: 'Camping Tents',
    rating: 3.3,
    features: ['Durable polyester tent body with true no-see-um mesh', '2-pole, quick-clip design provides easy setup'],
    description: 'For car camping or even backpacking, the Alpine Mountain Gear Weekender Tent 3-person dome tent is simple to set up and has all the fixings needed to transform your weekend into an adventure.',
    size: 'three-person',
    available: true,
    color: 'grey'
},
{
    brand:'Coleman',
    name: 'Skydome 2-Person Tent',
    price: 90.00,
    type: 'Camping Tents',
    rating: 4.8,
    features: ['Nearly vertical walls offer 20% more headroom than traditional Coleman dome tents', 'Wider door makes it easier to move air beds, sleeping bags and other gear in and out of the tent'],
    description: 'With plenty of room to stretch out inside and a quick setup that takes less than 5 minutes, the Coleman Skydome 2-person tent is great for going camping with your best buddy.',
    size: 'two-person',
    available: false,
    color: 'blue nights'
},
{
    brand:'Rugged Road',
    name: '85 V2 Cooler',
    price: 400.00,
    type: 'Hard-sided Coolers',
    rating: 5.0,
    features: ['Ultralight design is less than half the weight of comparable coolers', 'Floats upright, even when fully loaded with ice and drinks'],
    description: 'Great for camping, road trips and big family picnics, the Rugged Road 85 V2 cooler is extremely lightweight and durable. Plus, it holds ice for days so you can keep fresh food and cold drinks handy.',
    size: '61 liters',
    available: true,
    color: 'Sahara Tan'
},
{
    brand:'Yeti',
    name: 'Tundra 65 Cooler',
    price: 350.00,
    type: 'Hard-sided Coolers',
    rating: 4.8,
    features: ['Tundra 65 cooler has a 57.6-liter capacity (61 qt.) that will hold 39 cans and plenty of ice; designed to accommodate long-neck bottles', 'The Interagency Grizzly Bear Committee has certified the Tundra 65 as a bear-resistant food container when used with 2 padlocks (not included), 1 on each of the front corners'],
    description: 'Most coolers come away from a life full of adventure with cracked corners, caved-in lids and busted hinges. Not the YETI Tundra 65. It\'s built tough to take the abuse that comes with the way you play.',
    size: '57.6 liters',
    available: true,
    color: 'Charcoal'
},
{
    brand: "Sea to Summit ",
    name: "Aeros Down Pillow",
    price: 64.95,
    type: "Down Pillow",
    rating: 4.3,
    features: ["Down", "Inflatable"],
    description:
      "As you drift off to sleep, your pillow won't slide off of your Sea to Summit mat (not included): the PillowLock™ system keeps your pillow right where it belongs",
    size: "large",
    available: true,
    color: "grey",
  },
  {
    brand: "Rumpl",
    name: "Stuffable Pillowcase",
    price: 40.00,
    type: "Camp Pillow",
    rating: 4.5,
    features: ["Synthetic", "Air"],
    description:
      "The included stuff sack lets you pack away your pillowcase, ensuring no nap gets left behind",
    size: "small",
    available: true,
    color: "blue",
  },
  {
    brand: "Poler ",
    name: "Camp Pillow",
    price: 21.93,
    type: "Pillow",
    rating: 4,
    features: ["Synthetic", "Air"],
    description:
      "Inflates easily and packs down as small as a russet potato in its integrated stuff sack, making it ideal for backpacking and travel adventures",
    size: "small",
    available: true,
    color: "blue",
  },
  {
    brand: "Exped",
    name: "Mega Pillow",
    price: 59.95,
    type: "Pillow",
    rating: 4.4,
    features: ["Synthetic", "Air"],
    description:
      "3D design with vertical sidewalls allow the top surface to run edge-to-edge with no tapering, maximizing the sleeping surface",
    size: "medium",
    available: true,
    color: "Moss Green",
  },
  {
    brand: "Cocoon ",
    name: "AirCore Hyperlight Pillow",
    price: 36.95,
    type: "Pillow",
    rating: 3.1,
    features: ["Synthetic", "Air"],
    description:
      "Inflatable air core under a layer of synthetic fill provides an adjustable level of support and comfort",
    size: "small",
    available: true,
    color: "blue",
  },
  {
    brand: "HEST",
    name: "Standard Pillow",
    price: 119,
    type: "Pillow",
    rating: 4,
    features: ["Synthetic", "Air"],
    description:
      "Inflates easily and packs down as small as a russet potato in its integrated stuff sack, making it ideal for backpacking and travel adventures",
    size: "small",
    available: true,
    color: "blue",
  }];

module.exports = {inventorySeed}